# -------------------------------------------------------
# Custom Pictures
# -------------------------------------------------------

avatar:
  enable: true
  url: /static/images/kamuyi.jpg

background:
  background_color: white

  enable_picture: true
  url: /static/images/miku.jpg
  css_size: cover
  css_position: 50%

# -------------------------------------------------------
# Custom Blur
# -------------------------------------------------------
blur:
  background_color: white

  hide_overflow: true

  gaussian_radius:
    top_navigator: 30
    header: 40
    footer: 40
  
  font:
    color: white
  

# -------------------------------------------------------
# Menu
# -------------------------------------------------------

menu:
  # Basic Menu
  Home: true
  Archives: true
  Categories: false
  Tags: false

  # Custom Menu
  # '/index' can be omitted
  # please add '/pages' as prefix
  # example:
  # [X]  About: /about/index       (need '/pages' as prefix)
  # [O]  About: /pages/about/index (preferred)
  # [O]  About: /pages/about
  About: /pages/about/index

menu_icons:
  enable: true
  # icon name docs: http://fontawesome.io/icons/
  Home: fa-home
  Archives: fa-archive
  Categories: fa-bookmark
  Tags: fa-hashtag
  About: fa-smile-o

# -------------------------------------------------------
# Social
# -------------------------------------------------------

social:
  github: https://github.com/heskeybaozi
  weibo: http://weibo.com/52hezhiyu

  # Email link, reference to https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/Creating_hyperlinks#E-mail_links
  email: mailto:hezhiyu233@foxmail.com


social_icons:
  enable: true
  # icon name docs: http://fontawesome.io/icons/
  github: fa-github-alt
  weibo: fa-weibo
  email: fa-envelope
  wechat: fa-weixin
  qq: fa-qq

# -------------------------------------------------------
# Page 404
# -------------------------------------------------------
page_404:
  # enable to use custom 404 page
  enable: true
  # filename of .md file path in your source dir
  # example:
  # after run command `hexo new page 404`
  # [X]  source_path: /404/index            (work dictionry is 'source')
  # [O]  source_path: 404/index.md
  # [O]  source_path: 404/index
  # [O]  source_path: 404                   ('/index' can be omitted)
  source_path: 404/index.md

# -------------------------------------------------------
# Comments System
# -------------------------------------------------------

# https://github.com/imsun/gitment#customize
gitment:
  enable: true
  github_id: HeskeyBaozi
  repository_name: blog-comments
  client_id: ad644ccf919a7545ebbd
  client_secret: 884e508e709165f838fe4f58d4af050970b88216
  per_page: 8
  max_comment_height: 250 # 250px

# -------------------------------------------------------
# Google Analytics
# -------------------------------------------------------

google_analytics:
  enable: true
  track_id: UA-111467225-1 # start with 'UA-', such as 'UA-XXXXX-X'


# -------------------------------------------------------
# Powered by
# -------------------------------------------------------
powered_by: Hexo Theme Lite