# -------------------------------------------------------
# Custom Pictures
# -------------------------------------------------------

avatar:
  enable: true
  url: /static/images/6828af33.jpg

background:
  url: /static/images/miku.jpg
  css_size: cover
  css_position: 50%
  

# -------------------------------------------------------
# Menu
# -------------------------------------------------------

menu:
  Home: true
  Archives: true
  Categories: true
  Tags: true
  About: /pages/about/index

menu_icons:
  enable: true
  Home: fa-home
  Archives: fa-archive
  Categories: fa-bookmark
  Tags: fa-slack
  About: fa-smile-o

# -------------------------------------------------------
# Social
# -------------------------------------------------------

social:
  github: https://github.com/heskeybaozi
  weibo: http://weibo.com/52hezhiyu
  email: hezhiyu233@foxmail.com


social_icons:
  enable: true
  github: fa-github-alt
  weibo: fa-weibo
  email: fa-envelope
  wechat: fa-weixin
  qq: fa-qq

# -------------------------------------------------------
# Powered by
# -------------------------------------------------------
powered_by: Hexo Theme Lite